site_name: Flask-Comment
site_description: Create comment component in Flask/Jinja2 template.
site_url: https://flask-comment.readthedocs.io
site_author: Frank Yu
docs_dir: docs
theme:
  name: material
  # custom_dir: docs/_templates
  # logo: _assets/white-logo.png
  # favicon: _assets/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github
  language: en
repo_url: https://github.com/yuxiaoy1/flask-comment
repo_name: yuxiaoy1/flask-comment
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yuxiaoy1/flask-comment
copyright: Copyright &copy; 2021 <a href="https://yuxiaoy.com/en" target="_blank" rel="noopener">Frank Yu</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
  - toc:
        permalink: True
nav:
  - Home: index.md
  - Quick Start: start.md
  - Configuration: configuration.md
  - Examples: examples.md
  - API Reference: api.md
  - Authors: authors.md
  - Changelog: changelog.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            heading_level: 2
      watch:
        - src/flask_comment
